kirt/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from kirt.settings import LOGIN_URL
from src.views import SignUp
from users.views import UserProfile

"""
All the URLs that can be possibly called by user are working here. 
"""

urlpatterns = patterns('',
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','src.views.index'),
    url(r'^addworker/','src.views.addworker'),
    url(r'^logout/$','src.views.my_logout'),
    url(r'^signup/$', SignUp.as_view(),
        name='signup_view'),
    url(r'^src/addadvance/','src.views.addadvance'),
    url(r'^src/promotions/','src.views.promotions'),
    url(r'^ajaxpromotions/','src.views.ajaxpromotions'),
    url(r'^previous_promotions/','src.views.previous_promotions'),
    url(r'^daily_attendance/','src.views.daily_attendance'),
    url(r'^ajax_daily_attendance/','src.views.ajax_daily_attendance'),
    url(r'^ajaxdetails/','src.views.ajaxdetails'),
    url(r'^ajaxrequest/','src.views.ajaxrequest'),
    url(r'^ajaxrequestpaid/','src.views.ajaxrequestpaid'),
    url(r'^popupadvance/','src.views.popupadvance'),
    url(r'^ajaxpopupadvance/','src.views.ajaxpopupadvance'),
    url(r'^particulars/','src.views.particulars'),
    url(r'^payslip/', 'src.views.payslip'),
    url(r'^return_advance/','src.views.return_advance'),
    url(r'^deleteworker/','src.views.deleteworker'),
    url(r'^jsreverse/', 'src.views.jsreverse'), 
    url(r'^user_profile', 'users.views.UserProfile'),  
) 

src/models.py
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.core.validators import MaxValueValidator, MinValueValidator   
from django.db import models
from django.contrib.auth.models import User
import datetime

# This error not yet shown
alphabets = RegexValidator(r'^[a-zA-Z ]*$', 'Only alphabets and spaces are allowed.')

class WorkerDetail(models.Model):
    """
    This model keeps all the details of workers at one place. And is 
    updated with a new record after the user submits "Add worker" form.
    All the fields are mendatory. The joining_date is kept default for 
    the ease of user. WHen a new worker is added, the status is by default
    added as true which signifies that the worker is currently working in 
    the organisation. When a worker gets deleted, it changes to false
    and the queries are used this way to show only the workers who are
    currently working. 
    """

    user = models.ForeignKey(User)
    first_name = models.CharField(max_length=100, validators=[alphabets])
    middle_name = models.CharField(max_length=100, validators=[alphabets], null=True, blank=True)
    last_name = models.CharField(max_length=100, validators=[alphabets])
    address = models.CharField(max_length=200)
    joining_date = models.DateField(default=datetime.date.today)
    basic_wage = models.FloatField(validators = [MinValueValidator(0)])
    provident_fund = models.FloatField(validators = [MinValueValidator(0)], null=True, blank=True, default=0)
    status = models.BooleanField(default=True)
    resigning_date = models.DateField(null=True, blank=True)

    def __unicode__(self):
        return '%s' % (self.first_name) + ' ' '%s' % (self.last_name)

class Promotions(models.Model):
    """
    Here, we store the promotions of worker salaries which are done from 
    time to time. The date field helps to keep the track of date, time
    and year of the same action.
    """
    user = models.ForeignKey(User)
    worker_id = models.ForeignKey(WorkerDetail)
    promoted_wage = models.FloatField(validators = [MinValueValidator(0)])
    on_date = models.DateField(default=datetime.date.today)

class MonthlyAttendance(models.Model):
    """
    This model keeps the attendance of all the workers and is accessed 
    anytime the salarysheet is accessed or searched backward. 
    """
    user = models.ForeignKey(User)
    worker_id = models.ForeignKey(WorkerDetail)
    attended_days = models.FloatField(null=True, blank=True, validators = [MinValueValidator(0)]) # Value not more than 31?
    overtime_hours = models.FloatField(null=True, blank=True)
    for_month = models.DateField(default=datetime.date.today)

class DailyAttendance(models.Model):
    """
    This tabel is used to store worker attendance on daily basis
    """
    user = models.ForeignKey(User)
    worker_id = models.ForeignKey(WorkerDetail)
    attendance = models.FloatField(null=True, blank=True)
    overtime = models.FloatField(null=True, blank=True)
    for_day = models.DateField(default=datetime.date.today)
    
class Advance(models.Model):
    """
    The advance values, which are to be entered for any worker or for any month
    are stored here. It is updated when a new advance value is added
    and is accessed when the salarysheet is dislayed.
    """
    user = models.ForeignKey(User)
    worker_id = models.ForeignKey(WorkerDetail)
    advance_amount = models.FloatField()
    advance_date = models.DateField(default=datetime.date.today)

class PaidSalary(models.Model):
    """
    This model stores the paid salaries for all workers along with
    date which tells about the paid salary for a particular month
    for a particular worker. 
    """   
    user = models.ForeignKey(User)
    worker_id = models.ForeignKey(WorkerDetail)
    paid_amount = models.FloatField(null=True, blank=True)
    payment_date = models.DateField(default=datetime.date.today)

class WageDescription(models.Model): 
    """
    This model was added initially to store the wage description
    for workers for particular months. But its not in use as 
    the purpose is served by run time calculations and else every entry
    will also be updated here and it will increase the response time
    which is not required.
    """
#   worker_id = models.ForeignKey(WorkerDetail)
#   daily_wage = models.FloatField()
#   monthly_wage = models.FloatField()
#   monthly_payable = models.FloatField()
#   net_payable = models.FloatField()

    user = models.ForeignKey(User)
    worker_id = models.ForeignKey(WorkerDetail)
    monthly_basic_wage = models.FloatField()
    overtime_wage = models.FloatField()
    monthly_wage = models.FloatField()
    amount_to_be_paid = models.FloatField()
    paid_amount = models.FloatField()
    for_month = models.DateField()

class Balance(models.Model):
    """
    This model is used to store balance amount left for any worker
    after a salary is paid. This is updated whenever a Pay Slip page 
    is accessed and the values for previous balance are taken into 
    account in next month automatically.
    """
    user = models.ForeignKey(User)
    worker_id = models.ForeignKey(WorkerDetail)
    balance_amount = models.FloatField()
    for_month = models.DateField(default=datetime.date.today)

src/views.py
from __future__ import division
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.db.models import Q
from src.models import *
from users.models import Profile
from src.forms import *
from django.db.models import Min
#import forms
import datetime
from django.db.models import Sum
from calendar import monthrange
from django.core.urlresolvers import reverse
from src.config import _MAN_HOURS_A_DAY
from src.config import _OVERTIME_WAGE_FACTOR
from src.config import _COMPANY_NAME
from src.config import _COMPANY_ADDRESS_PART_1
from src.config import _COMPANY_ADDRESS_PART_2
#for payslip
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle
from io import BytesIO
from django.views.generic import View
from users.views import UserProfile




# These two variables are used >7 times in this file, so are declared 
# here only and refers to the current month and year.
this_month = int(datetime.date.today().month)
this_year = int(datetime.date.today().year)

@login_required
def index(request):
    """
    This view is meant to redirect the user to first add a worker, 
    before going anywhere when using Kirt for the first time. Else it 
    redirects to the salarysheet.
    """
    user = request.user
    profile = Profile.objects.filter(user=request.user.id)
    if profile:
        if not WorkerDetail.objects.filter(user=user) or not WorkerDetail.objects.filter(status=1, user=user):
            return HttpResponseRedirect(reverse("src.views.addworker"))
        else:
            return render(request,'src/index.html',{})

    else:
        """If user don't have an active profile, he/she will 
        automatically get redirected to profile page."""
        return HttpResponseRedirect(reverse("users.views.UserProfile"))

@login_required
def my_logout(request):
    """
    The logout function imports logout from the views of django.auth,
    redirects to the index view and then the login page is renderd
    again.
    """
    from django.contrib.auth.views import logout
    logout(request)
    return HttpResponseRedirect(reverse("src.views.index"))

class SignUp(View):
    """Class that handels SignUp requests.
    request: Http Request.
    pass: get(self, request), if get request. Else post(self,request).
    """
    form_class = RegisterForm
    template_name  = 'registration/registration_form.html'


    def get(self, request, *args, **kwargs):
        """Returns SignUp form."""
        form = self.form_class()
        return render(request, self.template_name, {'form': form})


    def post(self, request, *args, **kwargs):
        """Handels post request for SignUp class and create user id."""
        form = self.form_class(request.POST)
        if form.is_valid():
            user = User.objects.create_user(form.cleaned_data['username'].lower(),
                    form.cleaned_data['email'],
                    form.cleaned_data['password'])
            user.save()

            return render(self.request, "registration/registration_complete.html")

def jsreverse(request):
    """
    This function reverse looks up the urls for the AJAX Requests and
    enalbles he developer to use dynamic URLs in JavaScript.
    """
    string_to_reverse = request.GET['string'];
    return HttpResponse(reverse(string_to_reverse))

@login_required
def addworker(request):
    """
    If a new worker is to be added, this view is parsed and a form is 
    generated to add description about a new worker. On submitting the 
    the same form, from same page, the model WorkerDetails gets updates
    with respective records and starts appearing in salarysheet.
    """
    if request.method == 'POST':
        user = request.user
        initiate_unique_obj = WorkerDetail(user=user)
        form = WorkerDetailForm(data=request.POST, instance=initiate_unique_obj)
        if form.is_valid():
            #try:
            workerdetail = form.save()
            request.session['success'] = 'success'
            wd = WorkerDetail.objects.get(id = workerdetail.id)
            monthlyattendance = MonthlyAttendance(worker_id = wd,\
            attended_days = 0, overtime_hours = 0,\
            for_month = workerdetail.joining_date, user=user)
            monthlyattendance.save()
            paidsalary = PaidSalary(worker_id = wd, paid_amount = None,\
            payment_date = workerdetail.joining_date, user=user)
            paidsalary.save()
            first_basic_wage = Promotions(worker_id = wd, promoted_wage =\
            workerdetail.basic_wage, on_date = workerdetail.joining_date, user=user)
            first_basic_wage.save()
            return HttpResponseRedirect(reverse("src.views.index"))
        else:
            message = "Please correct the errors below"
            form = WorkerDetailForm(request.POST)
            return render(request,'src/addworker.html',{'WorkerDetailForm':form,
            'message':message })
			
            # except:
              #  message = "Sorry, there were invalid values in the form! "
               # url = reverse("src.views.addworker")
                #return render(request, 'src/error.html', {'message':message,\
                 #   'url':url})
    else:
        form = WorkerDetailForm()
    return render(request,'src/addworker.html',{'WorkerDetailForm':form})

@login_required
def daily_attendance(request):
    """
    This view displays the list of the employees who are currently working
    to add their attendance for today or for the date which it has not yet 
    been added.
    """
    user = request.user
    detail_list = []
    temp_today = datetime.date.today()

    attendance_date = request.GET.get('attendance_date')
    if attendance_date is not None:
        temp_today = datetime.datetime.strptime(attendance_date,'%d-%m-%Y')

    temp_this_month = int(temp_today.month)
    temp_this_year = int(temp_today.year)

    if this_month == temp_this_month:
        active_worker_ids = WorkerDetail.objects.values('id').filter(status = 1, user=user)
        for ids in active_worker_ids:
            if not PaidSalary.objects.filter(worker_id_id = ids['id'],\
                payment_date__month=temp_this_month, payment_date__year=temp_this_year, user=user).exists():
                new_obj = PaidSalary(worker_id_id = ids['id'], paid_amount = None,\
                          payment_date = temp_today, user=user)
                new_obj.save()

    unpaid_workers = PaidSalary.objects.values('worker_id_id').filter(paid_amount__isnull=True).\
    filter(payment_date__month = temp_this_month, user=user)

    allworkers = WorkerDetail.objects.values('id').filter(id__in = \
    unpaid_workers).filter(status = 1, user=user).filter(joining_date__lte = \
    temp_today)

    for worker in allworkers:
        if  DailyAttendance.objects.filter(worker_id = worker['id']).\
        filter(for_day = temp_today, user=user).exists():
            pass
        else:
            worker_object = WorkerDetail.objects.get(pk=worker['id'])
            new_object = DailyAttendance(worker_id = worker_object,\
            overtime = 0, attendance = 0, for_day = temp_today, user=user)
            new_object.save()
            pass

        if MonthlyAttendance.objects.filter(worker_id = worker['id']).\
        filter(for_month__month = temp_this_month, user=user).filter(for_month__year
        = temp_this_year).exists():
            pass
        else:
            worker_object = WorkerDetail.objects.get(pk=worker['id'])
            new_object = MonthlyAttendance(worker_id = worker_object,\
            attended_days = 0, overtime_hours = 0, for_month = temp_today, user=user)
            new_object.save()
        pass
    """
    for value in allworkers:
        worker_dict = {}

        details = WorkerDetail.objects.values('first_name', 'last_name',
        'address').filter(status = 1, user=user).filter(id = value['id'])

        daily_attendance = DailyAttendance.objects.values('attendance').\
        filter(worker_id = value['id']).filter(for_day = datetime.\
        date.today()).filter(worker_id__status = 1, user=user)

        daily_overtime = DailyAttendance.objects.values('overtime').\
        filter(worker_id = value['id']).filter(for_day = datetime.\
        date.today()).filter(worker_id__status = 1, user=user)

        worker_dict['worker_id'] = value['id']

        for item in details:
            worker_dict['first_name'] = item['first_name']
            worker_dict['last_name'] = item['last_name']
            worker_dict['address'] = item['address']
        for item in daily_attendance:
            worker_dict['daily_attendance'] = item['attendance']
        for item in daily_overtime:
            worker_dict['daily_overtime'] = item['overtime']
        detail_list.append(worker_dict)
    """

    attendance_marked_dates = DailyAttendance.objects.values_list('for_day').filter(user=user).distinct()
    date_list = []
    for a in attendance_marked_dates:
      if a[0] != datetime.date.today():
          date_list.append(a[0].strftime('%d-%-m-%Y'))

    mindate = WorkerDetail.objects.values_list('joining_date').filter(user=user).aggregate(Min('joining_date')) 
    min_joining_month = int(mindate['joining_date__min'].month)
    min_joining_date = mindate['joining_date__min'].strftime('%d-%-m-%Y')

    unpaid_workers = PaidSalary.objects.values('worker_id_id').filter(paid_amount__isnull=True).\
    filter(payment_date__month = temp_this_month, user=user)

    workerDetail_attendance = DailyAttendance.objects.filter(for_day = temp_today\
    ).filter(worker_id_id__in = unpaid_workers, user=user).order_by('worker_id_id').\
    select_related('worker_id').filter(worker_id__status = 1).\
    filter(worker_id__joining_date__lte = temp_today).all()

templates/src/addadvance.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Add advance {% endblock %}
{% block extrastyle %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/navbar.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/common.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/flatty.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/addworker.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/addadvance.css">

    <script src="{{ STATIC_URL }}js/humane.min.js"></script>
  {% if message %}
    <script>
      {% if success %}
        humane.addnCls = 'humane-success'
      {% endif %}
        humane.log('{{message}}', {timeout: 50000});
    </script>
  {% endif %}


{% endblock %}

{% block content %}

    
    <div class="center">
    <div class="notifications">
</div>
    <form method="POST" action=''>
    <!--{% if message %}
    <div class="alert alert-danger">
        {{message}}
    </div>
    {% endif %}-->
        {% csrf_token %}
        <legend> <h1><a href="{% url 'src.views.index' %}" class="glyphicon glyphicon-chevron-left small"> </a>Add advance</h1> </legend>
            {{AdvanceForm.as_p}} 
            <input class="btn btn-info btn-large" type = "submit" value="Submit" style="font-size:1.3em">
        
    </form>
</div>

{% endblock %}
{% block extrajs %}
    <script src="{{ STATIC_URL }}js/addworker.js"></script>
{% endblock %}

templates/src/addworker.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Add worker {% endblock %}
{% block extrastyle %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/navbar.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/common.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/addworker.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery-ui.css">
    <script src="{{ STATIC_URL }}js/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui.min.js"></script>

	<script type=text/javascript>
           $(document).ready(function(){

            $('#id_joining_date').datepicker({
		changeMonth: true, //this option for allowing user to select month
		changeYear:  true, //this option for allowing user to select from year range
                dateFormat: 'yy-mm-dd'
            });

	    $('#id_date').datepicker( "option", "showAnim", "clip" );
            });
	</script>

{% endblock %}

{% block content %}

    
    <div class="center">
  {% if message %}
  <div class="alert alert-danger">
  <div class="toggle"></div>
    <div class="messages">
      <p class="message"><i class="glyphicon glyphicon-exclamation-sign" style="color:#a94442;"></i> Please enter valid inputs</p>
    </div>
  </div>
  {% endif %}
    <form method="POST" action=''>
        {% csrf_token %}
        <legend> <h1>Add worker</h1> </legend>
            {{WorkerDetailForm.as_p}} 
            <input class="btn btn-info btn-large" type = "submit" value="Submit" style="font-size:1.3em">
        
    </form>
   
   
</div>
{% endblock %}
{% block extrajs %}
    <script src="{{ STATIC_URL }}js/addworker.js"></script>
{% endblock %}

templates/src/daily_attendance.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Daily attendance {% endblock %}
{% block extrastyle %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/navbar.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/particulars.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/backbutton.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery-ui.css">
    <script src="{{ STATIC_URL }}js/jquery.min.js"></script>

	<script type=text/javascript>
           $(document).ready(function(){
		var availableDates = {{date_list|safe}};
		var currentTime = new Date()
		var minDate = new Date(currentTime.getFullYear(), currentTime.getMonth(), +1);
                var current_month = minDate.getMonth() +1;
		if (current_month ==  {{min_joining_month}})
		       { minDate = '{{min_joining_date}}'; }
		var maxDate =  new Date(currentTime.getFullYear(), currentTime.getMonth() +1,0); // one day before next month
		//console.log(minDate);
		//console.log(maxDate);
	
		function available(date) {

		    dmy = date.getDate() + "-" + (date.getMonth()+1) + "-" + date.getFullYear();
		    
		  if ($.inArray(dmy, availableDates) != -1) {
		    return [false, "","unAvailable"];
		  } else {
		    return [true,"","Available"];
		  }
		}

		    $('#id_date').datepicker({
			changeMonth: true, //this option for allowing user to select month
			changeYear:  true, //this option for allowing user to select from year range
		        dateFormat: 'dd-mm-yy',
			
			beforeShowDay: available, 
			minDate: minDate,
			maxDate: 0,
		    }) 
		 $("#id_date").datepicker("setDate",'{{date}}');
		});
	</script>


{% endblock %}

{% block content %}
<div class="container"> 
  <div class="inner" style="width:80%; display:block; margin-left: auto; margin-right: auto;">
    <div class="font"> 

<!--      <div class="row">
            <div class="col-sm-6 col-md-4 col-lg-3">
              
            </div>
     </div> -->

        <div class="col-md-12"> <h3 style ="color:#428BCA"> <a href="{% url 'src.views.index' %}" class="glyphicon glyphicon-chevron-left small"> </a>Attendance: <input style ="color:#000; width: 20%; font-size:18px;" type="" id="id_date" placeholder="Attendace Date" data-toggle=tooltip title="Date" aria-label="..." > </h3> </div>
       <hr>

      <div class="row"> 
         <br><br><br>         
      </div>
        {% for value in workerDetail_attendance %}  
        
          <form action="" method="">
          <div class="text-left"> 
            <div class="col-sm-6 col-md-4">{{ forloop.counter }}{% if value.worker_id.middle_name == "" %}
                                           {{value.worker_id.first_name}} {{value.worker_id.last_name}}
                                           {% else %}
                                           {{value.worker_id.first_name}} {{value.worker_id.middle_name}} {{value.worker_id.last_name}}
                                           {% endif %}</div>
            
            <div class="col-sm-6 col-md-4 col-lg-3">
              <input type="checkbox" id="attendance_{{value.worker_id_id}}" data-toggle=tooltip title="Present/Absent" class="attendance" aria-label="..." {% if value.attendance == 1 %} checked {% endif %}>
            </div>

            <div class="clearfix visible-sm-block"></div>
            <div class="col-sm-6 col-md-4 col-lg-3">
              <input type="number" min="0" max="10" data-toggle=tooltip title="Overtime hours for the day" id="overtime_{{value.worker_id_id}}" class="overtime" placeholder="Overtime" value="{{value.overtime}}">
            </div>
            <div class="clearfix visible-sm-block"></div>
            
            {# Just to add horizontal line for separation on medium and extra small screens #}
            <span class="visible-xs-block visible-sm-block"> <hr> </span> 
          </div>
         </form>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block extrajs %}

<script type="text/javascript">
    var reverseurl = "{% url 'src.views.jsreverse' %}";

    function reverse(urlstring, callback) {
        if (typeof callback != "function") {
            return false;
            }
            
        $.get(reverseurl + "?string=" + urlstring, callback);
            }
</script>
<script type="text/javascript" src="{{ STATIC_URL }}js/daily_attendance.js">
</script>


{% endblock %}

templates/src/details.html
<html>
  <head>
    <meta charset="urf-8">
    <title>Add worker</title>
<style>
.left{
width: 80%;
background-color: #eee;
color: rgb(58,58,58);
font-family: Impact, Charcoal, sans-serifs
}
	</style>
  </head>

  <body class="left">
    <form method="POST" action=''>
    {% csrf_token %}
    {{AdvanceForm.as_p}}
	{{MonthlyAttendanceForm.as_p}}
    {{PaidSalaryForm.as_p}}
    <input type = "submit" value="submit">
    </form>
    </body>
</html>	

templates/src/dialog.html
<div id="dialog-form" title="Create new user">
  <p class="validateTips">All form fields are required.</p>

  <form>
  <fieldset>
    <label for="name">Name</label>
    <input type="text" name="name" id="name" class="text ui-widget-content ui-corner-all" />
    <label for="email">Email</label>
    <input type="text" name="email" id="email" value="" class="text ui-widget-content ui-corner-all" />
    <label for="password">Password</label>
    <input type="password" name="password" id="password" value="" class="text ui-widget-content ui-corner-all" />
  </fieldset>
  </form>
</div>

templates/src/error.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Error {% endblock %}
{% block extrastyle %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/navbar.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/common.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/form.css">
{% endblock %}

{% block content %}
<div class="container">
    <div class="center">
        <h4> {{message}} </h4> 
        <h4> <a href="{{url}}"> You can try again.</a> </h4>
    </div>
</div>
{% endblock %}

templates/src/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Home {% endblock %}
{% block extrastyle %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/navbar.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/common.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/index.css">
    
{% endblock %}
{% block content %}
      <div class="container">
      <div class=section>
	<div class="row">
		    <div class="col-sm-6 col-md-6">
			<a href="{% url 'src.views.daily_attendance' %}" >
			    <div class="tile">
				 
				    <div class=line_seprator></div>
				    <span class=tile__text>Daily Attendance</span>
		   	    </div>
			</a>
		    </div>
	<div class="clearfix visible-xs-block"></div>
		    <div class="col-sm-6 col-md-6">
			<a href="{% url 'src.views.ajaxdetails' %}" >
			    <div class="tile">
				 
				    <div class=line_seprator></div>
				    <span class=tile__text>Salary Sheet </span>
		   	    </div>
			</a>
		    </div>
	<div class="clearfix visible-xs-block"></div>
	</div>
	<div class="row">
		    <div class="col-sm-6 col-md-6">
			<a href="{% url 'src.views.addadvance' %}" >
			    <div class="tile">
				 
				    <div class=line_seprator></div>
				    <span class=tile__text>Add Advance</span>
		   	    </div>
			</a>
		    </div>
	<div class="clearfix visible-xs-block"></div>
		    <div class="col-sm-6 col-md-6">
			<a href="{% url 'src.views.promotions' %}">
			    <div class="tile">
				 
				    <div class=line_seprator></div>
				    <span class=tile__text>Promotions</span>
		   	    </div>
			</a>
		    </div>
	<div class="clearfix visible-xs-block"></div>
      </div>    
      </div>  
    
{% endblock %}

templates/src/popup.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
    <title>Dialog demo</title>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/jquery-ui.css" />
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui.min.js"></script>
    <script type="text/javascript">
        var $dialog; 
        $(document).ready(function () {
            $dialog = $('<div></div>')
            .dialog({
                autoOpen: false,
                open: function ()
            {
                $(this).load('test2.html');
            },         
            height: 400,
            width: 400,
            title: 'Test2'
            });

        
        });

        function showDialog() {
            $dialog.dialog('open');
            return false;}
 </script>
<script type="text/javascript">
function showUrlInDialog(url){
  $.ajax({
    url: 'dialog.html',
    success: function(data) {
      $("#dialog-form").load(data).dialog({modal:true}).dialog('open');
    }
  });
} 
        

    </script>
</head>
<body>
<!-- Manual -->
<button id="Button2" onclick="showDialog();">Open</button>
<a href="" id="Butt" onclick="showUrlInDialog();">Open</button>
</body>
</html>